name: spider

on:
  schedule:
    - cron: "30 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        npm install
        npm update bangumi-data
        node spider.js
    - name: Commit files
      run: |
        git config --local user.email "soekibun@gmail.com"
        git config --local user.name "ekibun"
        time=$(date "+%Y-%m-%d %H:%M:%S")
        git commit -m "Update at ${time}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}